%------------------XXXX++++++ INICIO DE PORTADA  ++++++XXXXX-----------------%
\begin{titlepage}

\newgeometry{left=2.5cm, bottom=3cm, top=2cm, right=2.5cm}

\tikz[remember picture,overlay] \node[opacity=1,inner sep=0pt] at (73.6mm, -124.25mm){\includegraphics{graficos/Picture_TitlePage.jpg}};

{\fontfamily{phv}\selectfont
\fontsize{25}{10.4}\fontseries{b}\selectfont
\vspace{13.5cm}
\begin{center}
\textbf{Detección de aportaciones fraudulentas en el seguro social ecuatoriano mediante algoritmos de machine learning}
\end{center}
\bigskip

\fontsize{12}{12}\selectfont
\fontseries{m}\selectfont
\vspace{2cm}
\centering
\begin{tabularx}{1\textwidth} {
  || >{\raggedright}X
  || >{\centering}X
  || >{\raggedleft\arraybackslash}X || }
 Titulación:\\Big Data y Ciencia de Datos\\
 & Alumno/a: Guatemal Aguilar, Cristian\\DNI: 1726307984
 & Convocatoria: \\
 Curso Académico\\ 2024-2025
  & Director/a del TFT:  Ortiz Vargas, Walter Andrés
%  & PRIMERA O SEGUNDA  \\
  & SEGUNDA \\
\end{tabularx}
 }
\end{titlepage}
%--------------------XXXX++++++ FIN DE PORTADA  ++++++XXXXX-----------------%